### ISSUE TITLE
How do I run the program?

### ISSUE THREAD

**Issue by PrincessDeSynk** [Aby-ss/Project-Nightfall#20]
Just curious as to how I'm meant to run and use this project. There's no instructions provided and I'm a bit confused where to start. Could I get some help?

**Comment by Aby-ss** [comment]
Hey, Although still in development, This project was idealized to be in one script yet I've broken the functions down to separate folders just to make it easier to access and run the individual features.

**Comment by PrincessDeSynk** [comment]
Thank you, I appreciate the reply! I can't wait to see how the project develops, great job so far!
